### ISSUE TITLE
Duplicating field_errors

### ISSUE THREAD

**Issue by Helghardt** [rehive/api#2]
![image](https://cloud.githubusercontent.com/assets/5997897/19819908/a9bd1aac-9d0b-11e6-80e6-ec80ab65c5dd.png)

**Comment by OdinsPlasmaRifle** [comment]
Are you wanting to remove the duplicate in the "message" part? Because I would think the duplicate in the "date" object is useful for pinpointing exactly which field is throwing an error.

**Comment by OdinsPlasmaRifle** [comment]
This has been changed to only display specific "error" types once within the universal `message` attribute. Multiple of the same errors will still be outputted for each field name.
